### ISSUE TITLE
Bg ini gimana ?

### ISSUE THREAD

**Issue by creath444** [MrTamfanX/fbtarget#3]
Unrecognized character \xA9; marked by <-- HERE after (<-- HERE near column 2 at prakasa-fb.pl line 2.

**Comment by creath444** [comment]
> Unrecognized character \xA9; marked by <-- HERE after (<-- HERE near column 2 at prakasa-fb.pl line 2.

**Comment by MrTamfanX** [comment]
Install dulu commandnya gan, cpan install Filter::Crypto
